### ISSUE TITLE
Feature: Ability to delete snippets from Command Palette

### ISSUE THREAD

**Issue by jakebathman** [jugyo/SublimeSnippetMaker#11]
For deleting snippets, it would be awesome to be able to delete them using an item in the Command Palette. 

Ideally, this would:
1. Be invoked, something like `SnippetMaker: Delete Snippet`
2. List all snippets in the palette for selection
3. Prompt "Are you sure?" with `Yes` | `No` options before deleting, with `No` selected by default to prevent accidental deletion. 
4. Delete the snippet file.
5. Show a notification in the status bar that the item was successfully deleted.

**Comment by jakebathman** [comment]
Since this functionality is included in PR #14, I'll close this issue. Thanks!

**Comment by braver** [comment]
I see that I need to do some ST2 backwards compatibility fixes, but a 2.0 release is coming very soon to provide this functionality.
