### ISSUE TITLE
Please specify a valid file name, i.e. `awesome.sublime-snippet`

### ISSUE THREAD

**Issue by R3l4x3** [jugyo/SublimeSnippetMaker#15]
I've tried to create a new snippet. I set the trigger, description and scope.

After input the file name (in my example `met.sublime-snippet`) I always get the error "Please specify a valid file name, i.e. `awesome.sublime-snippet`"

I get this error whatever file name I use.

What am I doing wrong or which further informations do you need?

**Comment by jakebathman** [comment]
Just making sure: are you entering `met` in the box, or `met.sublime-snippet`?

**Comment by braver** [comment]
@R3l4x3 

- what version of Sublime are you using?
- what operating system are you on?
- do you have a custom snippet_location or are you just using the default settings?
- can you try creating a file in `<Sublime Packages dir>Packages/User/Snippets` manually?

**Comment by R3l4x3** [comment]
Thank you for your answers. I think the problem was, that there was no `Snippets` folder in my `Packages/User` directory. After creating the `Snippets` folder I can create custom snippets. 

Thanks!

**Comment by braver** [comment]
Ok, that is a bug actually, thanks for reporting!
