### ISSUE TITLE
[feature request] Add setting for snippets path

### ISSUE THREAD

**Issue by redgluten** [jugyo/SublimeSnippetMaker#16]
Hi, thanks a lot for the great package, I use it daily and it saves me a ton of time. 👍

I have one request though: as I’m using version control on my snippets and macros I put them together in a specific directory so I need to move the new snippets manually each time. It would be neat to have a setting to change the default path for the snippets.

**Comment by braver** [comment]
If you open the package settings, you can set the “snippet_location” to a specific directory. Let me know if that works for you!

**Comment by redgluten** [comment]
Oh I somehow missed the package’s settings in the menu before. It works fine if I put the setting into the “Settings (Sublime Text 2)” file (thanks!) although it strangely tells me “_The settings file "res://Packages/SublimeSnippetMaker/SnippetMaker.sublime-settings" could not be opened_” if I try to open the “Settings” file. I’m using ST3 build 3149.

**Comment by braver** [comment]
Hm, may be bug in there, thanks for letting me know!
