### ISSUE TITLE
Edit Snippet does nothing

### ISSUE THREAD

**Issue by reagle** [jugyo/SublimeSnippetMaker#17]
Just installed to try, select `SnippetMaker: Edit Snippet` from command panel and nothing happens; no list of snippets in scope is presented.

build 4143

**Comment by braver** [comment]
Do you have any snippets that you created using this plugin?

**Comment by reagle** [comment]
No, does it only work for those?

**Comment by braver** [comment]
Yes, it only manages snippets that are in the configured folder.

**Comment by reagle** [comment]
Ok, thanks; you could mention this on your README.
