### ISSUE TITLE
update

### ISSUE THREAD

**Issue by MHTaleb** [jugyo/SublimeSnippetMaker#18]
Hi

First this plugging is awsome, I congrat you for this great work

My issue:

all my js code is jquery based, whenever I try to create a snippet I go manualy and check for $ to add an \ so the snippet works fine

would you add this mechanisme ?
to check for special characters ??

thanks

**Comment by braver** [comment]
Thanks for reporting. It's probably just the `$` because they're used to mark tab positions inside the snippet.
