### ISSUE TITLE
Doesn’t work with iCloud alias

### ISSUE THREAD

**Issue by cjaoude** [jugyo/SublimeSnippetMaker#19]
Throws the _Please specify a valid file name_ error if the `Package/Users/Snippets` folder is aliased to iCloud.

**Comment by braver** [comment]
Interesting, I’d have to investigate exactly what trips it up. IIRC it’s just python libs that work with the file system, might not be something we can actually fix..

**Comment by braver** [comment]
I don't understand exactly what you mean when you say "aliased to iCloud". An alias isn't something Sublime Text can work with, it will simply not load the snippets that are inside the aliased folder. A symlink does work, but even then it's not guaranteed that Sublime Text will update for new or modified files (in some cases it doesn't get updated for changes in the symlinked files and it's not strictly supported anyway). So, if it's supposed to work, but doesn't, that's a limitation of Sublime Text and not specifically this package.

**Comment by cjaoude** [comment]
Hi @braver I believe you are right. I noticed this just recently aliasing a project file. Sublime doesn't know what to do with it. Then I symlinked the same file and it worked. So I'll try symlinking the snippets folder too.

Tnx
