### ISSUE TITLE
Changing directory for new snippets

### ISSUE THREAD

**Issue by dukasvili** [jugyo/SublimeSnippetMaker#5]
How can I change destination directory for new snippets? I sort all my snippets in subdirectories in User folder, depending on the language, and option to choose destination from your plugin, in the creation process  would be nice...

**Comment by math2001** [comment]
I too sort my snippet, be even more: there is a folder per langage. So I was thinking we could use the scope to sort them (only the main one, like `source.python`). @jugyo if i do a pr, would you consider it?

**Comment by ctf0** [comment]
Yeah sure :)

**Comment by braver** [comment]
@math2001 I'm now maintaining this repo. In the `dev` branch I'm building the next release (don't want to put this on master yet until we're on tagged releases). It adds a configurable folder to store the snippets in, which helps. But it would be much nicer to take the main scope and create subfolders, as you suggest. I don't really see myself coding this on short term, so if you're still up for a PR, I would definitely consider (and applaud!) it.

**Comment by braver** [comment]
There is now a configurable snippets dir in 2.0. Should solve most of this.
